packages:
  - 'website'
  - 'packages/*'
  - 'external/egs-core/packages/*'
  - 'external/egs-core/packages/loaders/*'
  - 'external/egs-core/packages/utils/*'
  - 'external/egs-core/tools/utils'
  - 'packages/splat-transform-native/*'
  - 'external/splat-dev-server'

minimumReleaseAge: 0

allowBuilds:
  esbuild: false
  sharp: false
  webgpu: false

catalog:
  'typescript': '^6.0.3'
  'tslib': '^2.8.1'

overrides:
  '@internal/utils': 'workspace:*'
  '@qunhe/egs-typings': 'workspace:*'
  '@qunhe/egs-lib': 'workspace:*'
  '@qunhe/egs': 'workspace:*'
  '@qunhe/egs-animation': 'workspace:*'
  '@qunhe/egs-texture-loader': 'workspace:*'
  '@qunhe/egs-gltf-loader': 'workspace:*'
  '@qunhe/egs-draco-loader': 'workspace:*'
  '@qunhe/egs-splat-loader': 'workspace:*'
  '@qunhe/egs-splat-utils': 'workspace:*'
  '@qunhe/egs-xr': 'workspace:*'
  '@manycore/aholo-splat-transform': 'workspace:*'
  '@manycore/aholo-splat-dev-server': 'workspace:*'
  '@manycore/aholo-splat-transform-linux-arm64-gnu': 'workspace:*'
  '@manycore/aholo-splat-transform-linux-x64-gnu': 'workspace:*'
  '@manycore/aholo-splat-transform-win32-arm64-msvc': 'workspace:*'
  '@manycore/aholo-splat-transform-win32-x64-msvc': 'workspace:*'
  '@manycore/aholo-splat-transform-darwin-arm64': 'workspace:*'
  '@types/node': '^22.20.0'
  'esbuild': '^0.28.1'
